[package]
name = "local-rpc"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true

[dependencies]
windows-sys = { version = "0.61.0", features = ["Win32_System_Rpc", "Win32_Foundation", "Win32_Security", "Win32_Security_Authorization"] }
