namespace:
  name: homelab
  create: false
kube-prometheus-stack:
  nameOverride: prometheus
  namespaceOverride: prometheus
  nodeExporter:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  kubelet:
    enabled: true
    serviceMonitor:
      https: true
  kubeStateMetrics:
    enabled: true
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      additionalScrapeConfigs:
        - job_name: 'kubelet'
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/\${1}/proxy/metrics
        - job_name: 'kubelet/cadvisor'
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/\${1}/proxy/metrics/cadvisor
      retention: 15d
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 500m
          memory: 500Mi
  grafana:
    enabled: false
  alertmanager:
    enabled: true
    alertmanagerSpec:
      retention: 120h
      resources:
        requests:
          cpu: 25m
          memory: 25Mi
        limits:
          cpu: 100m
          memory: 100Mi
  prometheusOperator:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 200Mi
  extraManifests: 
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: prometheus
        annotations:
          "helm.sh/hook": pre-install
kubernetes-ingress:
  nameOverride: custom-ingress-controller
  prometheus: ingress
  namespace:
    create: true
  controller:
    kind: Deployment
    replicaCount: 1
    image:
      repository: haproxytech/kubernetes-ingress
      tag: "3.0.1"
    service:
      type: LoadBalancer
      tcpPorts:
        - name: k3s
          port: 6443
          targetPort: 6443
    initContainers:
      - name: debug-init
        image: busybox
        command: 
        - sh
        - -c
        - |
          echo "Debug init starting at $(date)"
          mkdir -p /etc/haproxy/maps
          ls -la /etc/haproxy/maps
          echo "Creating necessary files"
          touch /etc/haproxy/maps/host.map
          touch /etc/haproxy/maps/path-exact.map
          echo "k3s.wsl                 default_kubernetes_https"> /etc/haproxy/maps/path-prefix.map
          touch /etc/haproxy/maps/sni.map
          echo "Current contents:"
          ls -la /etc/haproxy/maps
          echo "Setting permissions for debug logs"
          echo "Debug init finished"
          sleep 30
        volumeMounts:
          - name: haproxy-maps
            mountPath: /etc/haproxy/maps
    extraVolumes:
      - name: haproxy-maps
        emptyDir: {}
      - name: haproxy-auxiliary-volume
        configMap:
          name: haproxy-auxiliary-configmap
      - name: sni-map
        configMap:
          name: sni-map-config
      - name: haproxy-config
        emptyDir: {}
    extraVolumeMounts:
      - name: haproxy-maps
        mountPath: /etc/haproxy/maps
      - name: haproxy-auxiliary-volume
        mountPath: /usr/local/etc/haproxy/haproxy-aux.cfg
        subPath: haproxy-auxiliary.cfg
      - name: sni-map
        mountPath: /etc/haproxy/maps/sni_6443.map
        subPath: sni_6443.map
        readOnly: true
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector: {}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
    config:
      ssl-passthrough: "true"
      ssl-passthrough-port: "6443"
      backend-check-interval: 10s
      backend-check-https-path: /healthz
      backend-check-https-verify: none
      logging: log stdout format raw local0 debug
    extraArgs:
      - --v=9
      - --log-level=trace
      - --healthz-bind-port=1042
      - --log-ingress-changes
      - --enable-ssl-passthrough
      - --maps-dir=/etc/haproxy/maps
    startupProbe:
      failureThreshold: 60
      periodSeconds: 10
      timeoutSeconds: 5
      httpGet:
        path: /healthz
        port: 1042
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      httpGet:
        path: /healthz
        port: 1042
        scheme: HTTP
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      httpGet:
        path: /healthz
        port: 1042
        scheme: HTTP
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 100Mi
    ingressClass: haproxy
    defaultBackend:
      enabled: false
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus