---
# Source: kubernetes-ingress/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-ingress-kubernetes-ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/version: 3.0.1
automountServiceAccountToken: true
---
# Source: kubernetes-ingress/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress-kubernetes-ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/version: 3.0.1
data:
  backend-check-https-path: /healthz
  backend-check-https-verify: none
  backend-check-interval: 10s
  logging: |
    log stdout format raw daemon debug
  ssl-passthrough: "true"
  ssl-passthrough-port: "443"
---
# Source: kubernetes-ingress/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-ingress-kubernetes-ingress
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/version: 3.0.1
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - services
  - namespaces
  - events
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  - ingresses/status
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.haproxy.org
  resources:
     - '*'
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ingress.v1.haproxy.org
  - ingress.v1.haproxy.com
  resources:
    - "*"
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - watch
---
# Source: kubernetes-ingress/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haproxy-ingress-kubernetes-ingress
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/version: 3.0.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: haproxy-ingress-kubernetes-ingress
subjects:
- kind: ServiceAccount
  name: haproxy-ingress-kubernetes-ingress
  namespace: ingress
---
# Source: kubernetes-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-kubernetes-ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/version: 3.0.1
  annotations:
spec:
  
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      appProtocol: http
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      appProtocol: https
      targetPort: https
    - name: quic
      port: 443
      protocol: UDP
      appProtocol: https
      targetPort: quic
    - name: stat
      port: 1024
      protocol: TCP
      targetPort: stat
    - name: prometheus
      port: 6060
      protocol: TCP
      targetPort: prometheus
  selector:
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/instance: haproxy-ingress
  externalIPs:
---
# Source: kubernetes-ingress/templates/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-ingress-kubernetes-ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/version: 3.0.1
spec:
  replicas: 1
  minReadySeconds: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-ingress
      app.kubernetes.io/instance: haproxy-ingress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-ingress
        app.kubernetes.io/instance: haproxy-ingress
    spec:
      enableServiceLinks: true
      serviceAccountName: haproxy-ingress-kubernetes-ingress
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
        runAsUser:  1000
        runAsGroup: 1000
      containers:
        - name: kubernetes-ingress-controller
          image: "haproxytech/kubernetes-ingress:3.0.1"
          imagePullPolicy: IfNotPresent
          args:
          - --default-ssl-certificate=ingress/haproxy-ingress-kubernetes-ingress-default-cert
          - --configmap=ingress/haproxy-ingress-kubernetes-ingress
          - --http-bind-port=8080
          - --https-bind-port=8443
          - --quic-bind-port=8443
          - --quic-announce-port=443
          - --ingress.class=haproxy
          - --publish-service=ingress/haproxy-ingress-kubernetes-ingress
          - --log=info
          - --prometheus
          - --v=9
          - --log-level=trace
          - --healthz-bind-port=1042
          - --log-ingress-changes
          - --enable-ssl-passthrough
          - --maps-dir=/tmp/haproxy
          securityContext:
            runAsNonRoot: true
            runAsUser:  1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: stat
              containerPort: 1024
              protocol: TCP
            - name: quic
              containerPort: 8443
              protocol: UDP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 1042
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 1042
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /healthz
              port: 1042
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              subPath: tmp
            - name: tmp
              mountPath: /run
              subPath: run
            - mountPath: /etc/haproxy/maps
              name: haproxy-maps
            - mountPath: /usr/local/etc/haproxy/haproxy-aux.cfg
              name: haproxy-auxiliary-volume
              subPath: haproxy-auxiliary.cfg
            - mountPath: /etc/haproxy/maps/sni_6443.map
              name: sni-map
              readOnly: true
              subPath: sni_6443.map
            - mountPath: /debug-logs
              name: debug-logs
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
        - emptyDir: {}
          name: haproxy-maps
        - configMap:
            name: haproxy-auxiliary-configmap
          name: haproxy-auxiliary-volume
        - configMap:
            name: sni-map-config
          name: sni-map
        - hostPath:
            path: /tmp/haproxy-debug-logs
            type: DirectoryOrCreate
          name: debug-logs
      initContainers:
        - command:
          - sh
          - -c
          - echo "Debug init starting"; ls -la /etc/haproxy/maps; chmod -R 777 /etc/haproxy/maps;
            echo "Debug init finished"; sleep 30
          image: busybox
          name: debug-init
          volumeMounts:
          - mountPath: /etc/haproxy/maps
            name: haproxy-maps
          - mountPath: /debug-logs
            name: debug-logs
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
---
# Source: kubernetes-ingress/templates/controller-crdjob.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: haproxy-ingress-kubernetes-ingress-crdjob-1
  namespace: ingress
  labels:
    app.kubernetes.io/name: haproxy-ingress-kubernetes-ingress-crdjob-1
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/version: 3.0.1
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: haproxy-ingress-kubernetes-ingress-crdjob-1
        app.kubernetes.io/instance: haproxy-ingress
    spec:
      restartPolicy: Never
      serviceAccountName: haproxy-ingress-kubernetes-ingress
      securityContext:
        runAsNonRoot: true
        runAsUser:  1000
        runAsGroup: 1000
      containers:
        - name: crd
          image: "haproxytech/kubernetes-ingress:3.0.1"
          imagePullPolicy: IfNotPresent
          command:
            - /haproxy-ingress-controller
            - --job-check-crd
          securityContext:
            runAsNonRoot: true
            runAsUser:  1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
---
# Source: kubernetes-ingress/templates/controller-ingressclass.yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/version: 3.0.1
spec:
  controller: haproxy.org/ingress-controller/haproxy
---
# Source: kubernetes-ingress/templates/controller-defaultcertsecret.yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: haproxy-ingress-kubernetes-ingress-default-cert
  namespace: ingress
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/version: 3.0.1
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMRENDQWhTZ0F3SUJBZ0lRTkpQMDRGTXZudjYvTXdaNDRjdUk4ekFOQmdrcWhraUc5dzBCQVFzRkFEQWcKTVI0d0hBWURWUVFERXhWcmRXSmxjbTVsZEdWekxXbHVaM0psYzNNdFkyRXdIaGNOTWpRd09EQXhNakV6TnpNMApXaGNOTWpVd09EQXhNakV6TnpNMFdqQWlNU0F3SGdZRFZRUURFeGRvWVhCeWIzaDVMV2x1WjNKbGMzTXVhVzVuCmNtVnpjekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOblBJdFVUWjlXWW5ybkEKS0ZMMUVSS0VMKzE3TENNc1NtZG9PWEFtSnp2aVM1cXVXS2xGbTJ4QlhDUEdNcUx2T1NUdFd6YktSekgzTXFQZAp5S2JlVjBBcE5WNjcwMldXeDYvVkk4MjNKZU9jcDFmMkZMd3BOdVNVMU5LNStuUVJ6c3Y1aWFuNXRXL2I3NnVjCnhiUjZDVDlpNDRMUnRQWWsvNHpNUXJ4YkRHZy96MlEvVzViOEJaM3dDT28zcGhnQkVtZFBRVzVLai9nTXJXUHUKQU9zTHc2ZmxQaGVtMXA3TGRENUZnUWhVdFZrY3RwMkxMY1FWUXRPYlN2RTEzNmRRTGNBSG9yeEd2UDI4MUpoNAozdGtpb2tOREdMdEpFNm9SV0VLUFFuOHVUOFMzMnlnR05FWFpxdHJtNHdrT0J2SFJWT0dzZGpMNlB2Tzlzcm1CCjIwWXRxN3NDQXdFQUFhTmdNRjR3RGdZRFZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUYKQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUI4R0ExVWRJd1FZTUJhQUZGYjU5b0Qxb0dQbQoySG84MkVGaUVKT2VWdGIxTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBZE53NWxKRktqMG1NVHlYelJURnBrCmVtTHVjVzVLR2hzSUd6Qk9ueEZ5alNNQ0o4dHJFYnQ5Q25Wa2RPcFNibktCaXBSUXJ1MlJGNmM2VWZjV29QdjkKY3crZWdXTXB5ZERVNERZb2FJYUhHOHM4K3dFSmRtWWFjUFR3R2o5NENFRjNIdkV0bE81cEw2cm5UQ1NvZUdkagprZncwS2JvZVNkUWkzQXVVMFR2N2ZZa3dhTlpvMVFwV1FvcXNWUi8vSzFxTkIwTGFOYnorR3NlSVJOQmx5a1p6Cks4bWhRbUt0aHl2SDZEaWYyaDVzc3R6MVJaQ212QlZ0dWRRUVZ2Y0E4UzNvcTl6NTdOeEt1UmFEazdGZk04UDUKWWllTGlneU44UEs1Y05aa2VNQ21HUVpEVkdIbDhTclpKVXBUbGJBUEVqa09iV042N240WXZnT0pTZHlQOTlncAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBMmM4aTFSTm4xWmlldWNBb1V2VVJFb1F2N1hzc0l5eEtaMmc1Y0NZbk8rSkxtcTVZCnFVV2JiRUZjSThZeW91ODVKTzFiTnNwSE1mY3lvOTNJcHQ1WFFDazFYcnZUWlpiSHI5VWp6YmNsNDV5blYvWVUKdkNrMjVKVFUwcm42ZEJIT3kvbUpxZm0xYjl2dnE1ekZ0SG9KUDJMamd0RzA5aVQvak14Q3ZGc01hRC9QWkQ5YgpsdndGbmZBSTZqZW1HQUVTWjA5QmJrcVArQXl0WSs0QTZ3dkRwK1UrRjZiV25zdDBQa1dCQ0ZTMVdSeTJuWXN0CnhCVkMwNXRLOFRYZnAxQXR3QWVpdkVhOC9ielVtSGplMlNLaVEwTVl1MGtUcWhGWVFvOUNmeTVQeExmYktBWTAKUmRtcTJ1YmpDUTRHOGRGVTRheDJNdm8rODcyeXVZSGJSaTJydXdJREFRQUJBb0lCQURtUEVxNXFaV3M5M054TAptcHhwcE94V3dHK3F1RHhIVFJaTXBia3NhL3ZZVHBCKytIRXJNdXFGenpxbyt1S3lBMUR0NU1meTVxT2VwdVJGCkRPeUVIMXlXUjBOVXNZWE1OZE1TcVZhSXl0dCtuMzZRU21SN0k4VitTMHV3MkMzcU10TVdpN20rZ3FNZjVSTmQKNTZWTkJycVlnSFVteEFLMFBsQlAvbWJXVE00VGFmWTl0bkI2RkVFcjNlTnJRZTViNzlmVmZWVlQxMmMwOXBDWgpqdVBDc2pXM21RZW1GMVFKOTloZW9XUEtSWHhkTU9ua1ZQRVlwbThlQnh2bkoxSTk5ZjN2c0FMVGZvV0dxa1NhCmhNOTBFc3FOUDVINXNyYTJsMlN4Q3V2QVZXTUg0RjhyOE9NY2JDYjRVbFRSblhld0xjLzBIaUtveFpPWUhSWi8KenJzSXhBRUNnWUVBNU02U1NuMVBudkZZWS9CSjFsYjBVNDc1SUtpNE5kSUhTeEhLWkd5ZDBTWXRCVnB1UThwbApDaFVpeXUzS0I1ZjVMazNGMVhRdnJGVVp6VE95REZ5VXA1VDk1OG1SS1RnY3Ivb3ZmLzRMNm1qcGFZWGdSZ2YwCjNtYWVHUjRIdUtlSk12RUoxSVdsMk5SWHB3V1RMN1h1aDVmbzRySFVoT0llTnNyOWJwUkZwZ0VDZ1lFQTg3SDEKTUxOQ2hvWkc3QXFTR2l0clNPQ3UyODNnVkFzR1VaUjJNQ1FlOUtUWDI1Rm9MMWs4a2ZLR24ydzIyVm13TElSKwpJV0M5S3VOOFkyTFA0eTBYYm9UeGpIQWpJZG5iemRVWmNXUmxPQWRKRGJBNWVrWkl5Z3Rhd0ZTcjR5eUpTbi9wCnRFVTNWYUpHYm1xUkJnTkRiNGNFOUFmYUpWRlNJekNJWmJ3M2Fic0NnWUJqdGVIcXRGRk9ZcjZ5VHJUZXcyWVcKUStndFkxbGptdk95c3o0UUpZVmc3OUlPMHluYVFRbG5LMjdPSUhJNmZQQUtUYm81R3pqclVPcTlraG0xYVdNZQo1TDhCazhXK3dNVS9xemVuLzM0UjJVWmV4Z2pHZkJFcUdtNHJZL3JaYmFsTW1kNCt6ejlIRHNKajl2bjlnTHRDCk8rRXhhVzNEdXdhUHVrWlhPaVpnQVFLQmdCOTFQWDJINW5LUEt1Q1ZqTDZzRkRGWUw3cFlIVGs4SXhpczNZVGgKWk0yWDZmV0NFN3pvL0JTckJnM1dYazQ0Y2JHTmVPcStIaTFIS0d0NytmSU5oQlRVUElvd2Y1aURFd2pERllHNQp3QWMzaVlxbTBRU2p4Z211NVl3bVlmbjFhZE9nSjM4SjRGYkJsKzN3KzcrVzlFR1ZZR0pRRVN6NERtNVVlWWNJCmdPNjVBb0dBUjdZeEEwQ0o2bzB2RFpoNXYvUmtXMy9BUUJkZ0FlOC9odEVWd2pyYTNMN3JINnpIZGw5KzF1RHIKRHpMNUdza2FMQmhVbFAwZFo0blBpaEdaYkkvb3IvM3NXbTRFWC9CM2ovQis4Y3doYmRZL0RFMHlmRE5ST3Z0agpkMzBmS1NGN2pWMHF3R3loMDFkd2wxYmVlSVM3cjUzbEFZMVZ6Q3pYLzRJVUtTbnBxdVk9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
