[package]
name = "home-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
windows-service = { workspace = true }
