apiVersion: v1
kind: ConfigMap
metadata:
  name: sni-map-config
  namespace: ingress
data:
  sni_6443.map: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-auxiliary-configmap
  namespace: ingress
data:
  haproxy-auxiliary.cfg: |
    frontend ssl_6443
      mode tcp
      bind 0.0.0.0:6443 name v4
      bind [::]:6443 name v6 v4v6
      tcp-request content reject if !{ req_ssl_hello_type 1 }
      tcp-request inspect-delay 5000
      tcp-request content set-var(sess.sni) req_ssl_sni
      tcp-request content set-var(txn.sni_match) req_ssl_sni,map(/etc/haproxy/maps/sni_6443.map)
      tcp-request content set-var(txn.sni_match) req_ssl_sni,regsub(^[^.]*,,),map(/etc/haproxy/maps/sni_6443.map)
      use_backend %[var(txn.sni_match),field(1,.)]
      default_backend ssl_6443

    backend ssl_6443
      mode tcp
      server https 127.0.0.1:8444 send-proxy-v2